import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { main } from '../src/cli.js';
import { generateIntegration } from '../src/generator.js';
import { createIntegrationPlan } from '../src/planner.js';
import { wireRepositoryRoutes } from '../src/route-handoff.js';
import { pathExists } from '../src/utils.js';

test('wireRepositoryRoutes creates Astro host route files additively after preview', async () => {
  const repoPath = await mkdtemp(path.join(os.tmpdir(), 'hts-route-handoff-'));
  const manifest = await createIntegrationPlan({
    integrationId: 'acme-campaign-v1',
    templatePath: 'templates/acme-campaign',
    framework: 'astro'
  });
  await generateIntegration(manifest, {
    repoPath,
    templatePath: 'templates/acme-campaign',
    framework: 'astro'
  });

  const preview = await wireRepositoryRoutes(manifest, { repoPath, dryRun: true });
  assert.equal(preview.status, 'passed');
  assert.equal(preview.summary.would_create, 5);
  assert.equal(await pathExists(path.join(repoPath, 'src/pages/index.astro')), false);

  const result = await wireRepositoryRoutes(manifest, { repoPath });
  assert.equal(result.status, 'passed');
  assert.equal(result.summary.created, 5);
  assert.equal(result.host_routes_modified, false);

  const aboutRoute = await readFile(path.join(repoPath, 'src/pages/about.astro'), 'utf8');
  assert.match(aboutRoute, /Generated by HTML-to-Storyblok/);
  assert.match(aboutRoute, /Source proposal: src\/integrations\/acme-campaign-v1\/route-proposals\/about\/page\.astro/);
  assert.match(aboutRoute, /import ImportedRoute from '\.\.\/integrations\/acme-campaign-v1\/route-proposals\/about\/page\.astro'/);
});

test('wireRepositoryRoutes blocks all writes when a host route already exists', async () => {
  const repoPath = await mkdtemp(path.join(os.tmpdir(), 'hts-route-handoff-collision-'));
  const manifest = await createIntegrationPlan({
    integrationId: 'acme-campaign-v1',
    templatePath: 'templates/acme-campaign',
    framework: 'astro'
  });
  await generateIntegration(manifest, {
    repoPath,
    templatePath: 'templates/acme-campaign',
    framework: 'astro'
  });
  await mkdir(path.join(repoPath, 'src/pages'), { recursive: true });
  await writeFile(path.join(repoPath, 'src/pages/about.astro'), '<p>Existing client route</p>\n');

  const result = await wireRepositoryRoutes(manifest, { repoPath });
  assert.equal(result.status, 'blocked');
  assert.equal(result.summary.blocked, 1);
  assert.match(result.routes.find((route) => route.slug === 'about').reason, /already exists/);
  assert.equal(await pathExists(path.join(repoPath, 'src/pages/index.astro')), false);
});

test('wire-routes CLI command previews route handoff without writing host routes', async () => {
  const repoPath = await mkdtemp(path.join(os.tmpdir(), 'hts-route-handoff-cli-repo-'));
  const workDir = await mkdtemp(path.join(os.tmpdir(), 'hts-route-handoff-cli-work-'));
  await captureStdout(async () => {
    await main([
      'node',
      'html-to-storyblok',
      'plan',
      '--integration-id',
      'acme-campaign-cli-v1',
      '--template',
      'templates/acme-campaign',
      '--framework',
      'astro',
      '--work-dir',
      workDir
    ]);
  });
  await captureStdout(async () => {
    await main([
      'node',
      'html-to-storyblok',
      'generate',
      '--manifest',
      path.join(workDir, 'integration-manifest.json'),
      '--repo',
      repoPath,
      '--template',
      'templates/acme-campaign',
      '--framework',
      'astro',
      '--work-dir',
      workDir
    ]);
  });

  const output = await captureStdout(async () => {
    await main([
      'node',
      'html-to-storyblok',
      'wire-routes',
      '--manifest',
      path.join(workDir, 'integration-manifest.json'),
      '--repo',
      repoPath,
      '--dry-run',
      '--json-summary',
      '--work-dir',
      workDir
    ]);
  });
  const result = JSON.parse(output);

  assert.equal(result.action, 'wire_repository_routes');
  assert.equal(result.status, 'passed');
  assert.equal(result.would_create_routes, 5);
  assert.equal(await pathExists(path.join(repoPath, 'src/pages/index.astro')), false);
});

async function captureStdout(callback) {
  const originalLog = console.log;
  let output = '';
  console.log = (value) => {
    output += `${value}\n`;
  };
  try {
    await callback();
  } finally {
    console.log = originalLog;
  }
  return output.trim();
}
