import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { main } from '../src/cli.js';
import { generateIntegration } from '../src/generator.js';
import { createIntegrationPlan } from '../src/planner.js';
import { wireRepositoryRoutes } from '../src/route-handoff.js';
import { pathExists } from '../src/utils.js';

test('wireRepositoryRoutes creates Astro host route files additively after preview', async () => {
  const repoPath = await mkdtemp(path.join(os.tmpdir(), 'hts-route-handoff-'));
  const manifest = await createIntegrationPlan({
    integrationId: 'acme-campaign-v1',
    templatePath: 'templates/acme-campaign',
    framework: 'astro'
  });
  await generateIntegration(manifest, {
    repoPath,
    templatePath: 'templates/acme-campaign',
    framework: 'astro'
  });

  const preview = await wireRepositoryRoutes(manifest, { repoPath, dryRun: true });
  assert.equal(preview.status, 'passed');
  assert.equal(preview.summary.would_create, 5);
  assert.equal(await pathExists(path.join(repoPath, 'src/pages/index.astro')), false);

  const result = await wireRepositoryRoutes(manifest, { repoPath });
  assert.equal(result.status, 'passed');
  assert.equal(result.summary.created, 5);
  assert.equal(result.host_routes_modified, false);

  const aboutRoute = await readFile(path.join(repoPath, 'src/pages/about.astro'), 'utf8');
  assert.match(aboutRoute, /Generated by HTML-to-Storyblok/);
  assert.match(aboutRoute, /Source proposal: src\/integrations\/acme-campaign-v1\/route-proposals\/about\/page\.astro/);
  assert.match(aboutRoute, /import ImportedRoute from '\.\.\/integrations\/acme-campaign-v1\/route-proposals\/about\/page\.astro'/);
  assert.match(aboutRoute, /STORYBLOK_PREVIEW_TOKEN/);
  assert.match(aboutRoute, /const story = Astro\.props\.story \|\| await htsFetchStoryblokDraft\(\)/);
  assert.match(aboutRoute, /HTS_STORYBLOK_STORY_SLUG = "acme-campaign-v1\/about"/);
  assert.match(aboutRoute, /data-hts-storyblok-source=\{htsStoryblokSource\}/);
  assert.match(aboutRoute, /data-hts-storyblok-slug=\{HTS_STORYBLOK_STORY_SLUG\}/);
});

test('wireRepositoryRoutes blocks all writes when a host route already exists', async () => {
  const repoPath = await mkdtemp(path.join(os.tmpdir(), 'hts-route-handoff-collision-'));
  const manifest = await createIntegrationPlan({
    integrationId: 'acme-campaign-v1',
    templatePath: 'templates/acme-campaign',
    framework: 'astro'
  });
  await generateIntegration(manifest, {
    repoPath,
    templatePath: 'templates/acme-campaign',
    framework: 'astro'
  });
  await mkdir(path.join(repoPath, 'src/pages'), { recursive: true });
  await writeFile(path.join(repoPath, 'src/pages/about.astro'), '<p>Existing client route</p>\n');

  const result = await wireRepositoryRoutes(manifest, { repoPath });
  assert.equal(result.status, 'blocked');
  assert.equal(result.summary.blocked, 1);
  assert.match(result.routes.find((route) => route.slug === 'about').reason, /already exists/);
  assert.equal(await pathExists(path.join(repoPath, 'src/pages/index.astro')), false);
});

test('wire-routes CLI command previews route handoff without writing host routes', async () => {
  const repoPath = await mkdtemp(path.join(os.tmpdir(), 'hts-route-handoff-cli-repo-'));
  const workDir = await mkdtemp(path.join(os.tmpdir(), 'hts-route-handoff-cli-work-'));
  await captureStdout(async () => {
    await main([
      'node',
      'html-to-storyblok',
      'plan',
      '--integration-id',
      'acme-campaign-cli-v1',
      '--template',
      'templates/acme-campaign',
      '--framework',
      'astro',
      '--work-dir',
      workDir
    ]);
  });
  await captureStdout(async () => {
    await main([
      'node',
      'html-to-storyblok',
      'generate',
      '--manifest',
      path.join(workDir, 'integration-manifest.json'),
      '--repo',
      repoPath,
      '--template',
      'templates/acme-campaign',
      '--framework',
      'astro',
      '--work-dir',
      workDir
    ]);
  });

  const output = await captureStdout(async () => {
    await main([
      'node',
      'html-to-storyblok',
      'wire-routes',
      '--manifest',
      path.join(workDir, 'integration-manifest.json'),
      '--repo',
      repoPath,
      '--dry-run',
      '--json-summary',
      '--work-dir',
      workDir
    ]);
  });
  const result = JSON.parse(output);

  assert.equal(result.action, 'wire_repository_routes');
  assert.equal(result.status, 'passed');
  assert.equal(result.would_create_routes, 5);
  assert.equal(await pathExists(path.join(repoPath, 'src/pages/index.astro')), false);
});

test('wireRepositoryRoutes generates live draft fetchers for Next and Nuxt routes', async () => {
  const nextRepoPath = await mkdtemp(path.join(os.tmpdir(), 'hts-route-handoff-next-'));
  const nextManifest = await createIntegrationPlan({
    integrationId: 'next-campaign-v1',
    templatePath: 'templates/acme-campaign',
    framework: 'next'
  });
  await generateIntegration(nextManifest, {
    repoPath: nextRepoPath,
    templatePath: 'templates/acme-campaign',
    framework: 'next'
  });
  const nextResult = await wireRepositoryRoutes(nextManifest, { repoPath: nextRepoPath, route: 'home' });
  assert.equal(nextResult.status, 'passed');
  const nextRoute = await readFile(path.join(nextRepoPath, 'src/app/page.jsx'), 'utf8');
  assert.match(nextRoute, /export const dynamic = 'force-dynamic'/);
  assert.match(nextRoute, /await htsFetchStoryblokDraft\(\)/);
  assert.match(nextRoute, /STORYBLOK_PREVIEW_TOKEN/);
  assert.match(nextRoute, /HTS_STORYBLOK_STORY_SLUG = "next-campaign-v1\/home"/);
  assert.match(nextRoute, /data-hts-storyblok-source=\{htsStoryblokSource\}/);
  assert.match(nextRoute, /data-hts-storyblok-slug=\{HTS_STORYBLOK_STORY_SLUG\}/);

  const nuxtRepoPath = await mkdtemp(path.join(os.tmpdir(), 'hts-route-handoff-nuxt-'));
  const nuxtManifest = await createIntegrationPlan({
    integrationId: 'nuxt-campaign-v1',
    templatePath: 'templates/acme-campaign',
    framework: 'nuxt'
  });
  await generateIntegration(nuxtManifest, {
    repoPath: nuxtRepoPath,
    templatePath: 'templates/acme-campaign',
    framework: 'nuxt'
  });
  const nuxtResult = await wireRepositoryRoutes(nuxtManifest, { repoPath: nuxtRepoPath, route: '/services' });
  assert.equal(nuxtResult.status, 'passed');
  const nuxtRoute = await readFile(path.join(nuxtRepoPath, 'pages/services.vue'), 'utf8');
  assert.match(nuxtRoute, /useAsyncData\('hts-services-storyblok-draft'/);
  assert.match(nuxtRoute, /if \(import\.meta\.client\) return null/);
  assert.match(nuxtRoute, /STORYBLOK_PREVIEW_TOKEN/);
  assert.match(nuxtRoute, /HTS_STORYBLOK_STORY_SLUG = "nuxt-campaign-v1\/services"/);
  assert.match(nuxtRoute, /:data-hts-storyblok-source="story \? 'storyblok-draft' : 'generated-fallback'"/);
  assert.match(nuxtRoute, /:data-hts-storyblok-slug="HTS_STORYBLOK_STORY_SLUG"/);
});

test('wireRepositoryRoutes gives manual handoff guidance for React and Vue routes', async () => {
  const reactRepoPath = await mkdtemp(path.join(os.tmpdir(), 'hts-route-handoff-react-'));
  const reactManifest = await createIntegrationPlan({
    integrationId: 'react-campaign-v1',
    templatePath: 'templates/acme-campaign',
    framework: 'react'
  });
  await generateIntegration(reactManifest, {
    repoPath: reactRepoPath,
    templatePath: 'templates/acme-campaign',
    framework: 'react'
  });

  const reactResult = await wireRepositoryRoutes(reactManifest, { repoPath: reactRepoPath, dryRun: true, route: 'home' });
  assert.equal(reactResult.status, 'skipped');
  assert.equal(reactResult.summary.skipped, 1);
  assert.equal(reactResult.manual_handoff.required, true);
  assert.deepEqual(reactResult.manual_handoff.frameworks, ['react']);
  assert.match(reactResult.routes[0].manual_handoff.reason, /React route registration depends/);
  assert.match(reactResult.routes[0].manual_handoff.route_proposal_file, /route-proposals\/home\/page\.jsx/);
  assert.ok(reactResult.routes[0].manual_handoff.steps.some((step) => /never expose Management API tokens/.test(step)));

  const vueRepoPath = await mkdtemp(path.join(os.tmpdir(), 'hts-route-handoff-vue-'));
  const vueManifest = await createIntegrationPlan({
    integrationId: 'vue-campaign-v1',
    templatePath: 'templates/acme-campaign',
    framework: 'vue'
  });
  await generateIntegration(vueManifest, {
    repoPath: vueRepoPath,
    templatePath: 'templates/acme-campaign',
    framework: 'vue'
  });

  const vueResult = await wireRepositoryRoutes(vueManifest, { repoPath: vueRepoPath, dryRun: true, route: '/services' });
  assert.equal(vueResult.status, 'skipped');
  assert.equal(vueResult.manual_handoff.required, true);
  assert.deepEqual(vueResult.manual_handoff.frameworks, ['vue']);
  assert.match(vueResult.routes[0].manual_handoff.reason, /Vue route registration depends/);
  assert.match(vueResult.routes[0].manual_handoff.route_proposal_file, /route-proposals\/services\/Page\.vue/);
});

async function captureStdout(callback) {
  const originalLog = console.log;
  let output = '';
  console.log = (value) => {
    output += `${value}\n`;
  };
  try {
    await callback();
  } finally {
    console.log = originalLog;
  }
  return output.trim();
}
